JavaScript capstone project
Hadi111jafari/capstone2-API-webapp pull request #56
Opened 2022-04-23 08:55 UTC by memelopez

### This PR implements: 🆕 💻 🔥 🆒 💯 
- Use of JavaScript to make the website dynamic and build single page app. ✔️ 
- Use of ES6 syntax. ✔️ 
- Use of ES6 modules. ✔️ 
- Use of callbacks and promises. ✔️ 
- Use of webpack. ✔️ 
- Use of AAA pattern for testing. ✔️ 
- Use of Jest for testing. ✔️ 
- Correct use of Gitflow. ✔️ 
- Sends and receives data from APIs. ✔️ 
- JavaScript asynchronous code. ✔️ 
- Code reviews between team members. ✔️ 
- A home page showing a list of POKEMONS 🐯 that can be "liked". ✔️ 
- A popup window with more data about the POKEMON 🦁 that shows and creates comments. ✔️ 
- A well documented README file that has a link to a video with an overview of project. ✔️ 
- No linter errors ✅

2022-04-23 10:43 UTC, FrederickMih requested changes
Hi @memelopez @Hadi111jafari  , 

A fantastic project so far!
There are some little issues that you still need to work on to prepare your project for the final evaluation but you are almost there! 


![](https://media.giphy.com/media/eykEJy5G46OLR1dpAf/giphy.gif)


# To Highlights

-  Git/GitHub workflow has been followed :heavy_check_mark: 
-  Linters are correctly set up :heavy_check_mark: 
-  Pull Request has a title and summary :heavy_check_mark: 
-  Home page and Comment popup works as expected :heavy_check_mark: 

## Suggested changes
- [x] **Video Presentation**: Hi team, your video presentation is really interesting. Please let's also highlight a piece of the code we find interesting or proud of making as the requirement says
- [ ] From your video presentation, it shows that the counter functions were get covered with unit tests but when I run the command `npm run test`, I get this console error.


![Screenshot from 2022-04-23 11-30-04](https://user-images.githubusercontent.com/63087491/164890846-4605ffd8-1655-4936-81af-19a87997dac5.png).

 Any idea?

If I'm not missing out on something, please let's make sure that these functions are covered with unit tests using the **Jest Framework**





Thanks :pray: 



_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-23 10:43 UTC, FrederickMih commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] Great README!. 
Please kindly fix this link. This will render our README professional:smiley:

2022-04-23 11:27 UTC, Hadi111jafari commented on README.md
> +This project is [MIT](./MIT.md) licensed.
Functions are covered with unit tests are in testing brunch, it is not merged.
You can check that.
We tried as much as we could explain the code, but there was time shortage that the video should not be longer than 5 minutes.
And the link for MIT license is updated.
@FrederickMih

2022-04-23 14:15 UTC, memelopez commented on README.md
> +This project is [MIT](./MIT.md) licensed.
#### Hi reviewers! 👋 

Thank you for your valuable feedback. We have made changes as requested:
- we have re-recorded the video to say what we are proud of in the code.
- we have fixed the link about the MIT license 
- and about the testing: we preferred not to merge the testing to our development branch, so it is a separate branch called testing. I hope this is not too inconvenient for you guys. 

Thanks again for your reviews and have a nice day! ✌🏼😘

2022-04-23 14:55 UTC, mmsesay approved these changes
Hi @memelopez & @Hadi111jafari, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-04-23 15:37 UTC, merged

2022-04-24 00:06 UTC, FrederickMih commented on README.md
> +This project is [MIT](./MIT.md) licensed.
> Functions are covered with unit tests are in testing brunch, it is not merged. You can check that. We tried as much as we could explain the code, but there was time shortage that the video should not be longer than 5 minutes. And the link for MIT license is updated. @FrederickMih

@memelopez @Hadi111jafari , great job for recording another video